Repository CS2113-AY1819S1-T16-4/main, pull requests merged in 2018-10, with the labels that each got.

#69 Schedule Feature V1.2.1 Branch
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/SchedulePanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/addressbook/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/ScheduleList.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/model/schedule/exceptions/DuplicateScheduleException.java
  src/main/java/seedu/address/model/schedule/exceptions/ScheduleNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/schedule/XmlAdaptedSchedule.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/java/seedu/address/ui/ScheduleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScheduleListCard.fxml
  src/main/resources/view/ScheduleListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.enhancement, type.story

#70 Schedule Feature V1.2.2 Branch Test case update
  src/main/java/seedu/address/commons/events/ui/SchedulePanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/ScheduleList.java
  src/main/java/seedu/address/model/schedule/Type.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/model/schedule/exceptions/DuplicateScheduleException.java
  src/main/java/seedu/address/model/schedule/exceptions/ScheduleNotFoundException.java
  src/main/java/seedu/address/storage/schedule/XmlAdaptedSchedule.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/java/seedu/address/ui/ScheduleListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/schedule/DateTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/TypeTest.java
  src/test/java/seedu/address/model/schedule/UniqueScheduleListTest.java
  src/test/java/seedu/address/model/schedule/VersionedScheduleListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
  src/test/java/seedu/address/testutil/schedule/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/schedule/ScheduleListBuilder.java
  src/test/java/seedu/address/testutil/schedule/TypicalSchedules.java
Labels: priority.high, type.enhancement, type.story

#73 V1.2.3 Schedule command new branch
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/model/schedule/EmployeeIdScheduleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/ScheduleList.java
  src/main/java/seedu/address/model/schedule/Type.java
  src/main/java/seedu/address/storage/schedule/XmlSerializableScheduleList.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/XmlScheduleListStorageTest/NotXmlFormatScheduleList.xml
  src/test/data/XmlScheduleListStorageTest/invalidAndValidScheduleScheduleList.xml
  src/test/data/XmlScheduleListStorageTest/invalidScheduleScheduleList.xml
  src/test/data/XmlSerializableScheduleListTest/duplicateScheduleScheduleList.xml
  src/test/data/XmlSerializableScheduleListTest/invalidScheduleScheduleList.xml
  src/test/data/XmlSerializableScheduleListTest/typicalSchedulesScheduleList.xml
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/schedule/TypeTest.java
  src/test/java/seedu/address/storage/XmlAdaptedScheduleTest.java
  src/test/java/seedu/address/storage/XmlScheduleListStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableScheduleListTest.java
  src/test/java/seedu/address/testutil/schedule/TypicalSchedules.java
Labels: priority.high, type.enhancement, type.story

#74 V1.2 Filter Command
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/DepartmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PositionContainsKeywordsPredicate.java
Labels: priority.high, type.story

#76 Expenses v1.2.1 Remove Expenses Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemoveExpensesCommand.java
  src/main/java/seedu/address/logic/commands/RemoveexCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveExpensesCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
Labels: priority.high, type.story

#75 V1.2.2 Updates to Filter Command
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Position.java
Labels: priority.high, type.enhancement, type.story

#95 UserGuide Update
  docs/UserGuide.adoc
Labels: update.documentation, v1.2

#98 Expenses v1.2.2 Updates on Expenses UI
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/ExpensesPanelSelectionChangedEvent.java
  src/main/java/seedu/address/ui/ExpensesCard.java
  src/main/java/seedu/address/ui/ExpensesListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ExpensesListCard.fxml
  src/main/resources/view/ExpensesListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.high, type.enhancement, v1.2

#97 DeveloperGuide Update
  docs/DeveloperGuide.adoc
  docs/images/filterCommandSequenceDiagram.png
Labels: priority.high, update.documentation, v1.2

#96 V1.2.3 Updates to Filter Command
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: priority.high, type.enhancement, v1.2

#99 Modify pay v1.2.1
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ModifyPayCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Bonus.java
  src/main/java/seedu/address/model/person/Salary.java
Labels: priority.high, type.story

#103 V1.2 Documentation update
  docs/DeveloperGuide.adoc
  docs/images/Schedule/Basic Sequence Diagram2.png
  docs/images/Schedule/schedule_class_diagram.png
Labels: priority.high, update.documentation, v1.2

#102 Expenses v1.2.3 Updates on Developer Guide: Expenses Feature
  docs/DeveloperGuide.adoc
Labels: priority.high, update.documentation, v1.2

#104 V1.2.4 Testcase for Filter Command
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high, update.testcase

#105 Updated Developer Guide for 3.2 Modify Pay Feature
  docs/DeveloperGuide.adoc
Labels: priority.high, update.documentation, v1.2

#106 Documentation guide update
  docs/DeveloperGuide.adoc
Labels: priority.high, update.documentation

#101 Recruitment1.2.1#55
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/RecruitmentListChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/RecruitmentPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/parser/AddRecruitmentPostCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/recruitment/Post.java
  src/main/java/seedu/address/model/recruitment/ReadOnlyRecruitmentList.java
  src/main/java/seedu/address/model/recruitment/Recruitment.java
  src/main/java/seedu/address/model/recruitment/RecruitmentList.java
  src/main/java/seedu/address/model/recruitment/UniqueRecruitmentList.java
  src/main/java/seedu/address/model/recruitment/VersionedRecruitmentList.java
  src/main/java/seedu/address/model/recruitment/exceptions/DuplicateRecruitmentException.java
  src/main/java/seedu/address/model/recruitment/exceptions/RecruitmentNotFoundException.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/recruitment/RecruitmentListStorage.java
  src/main/java/seedu/address/storage/recruitment/XmlAdaptedRecruitment.java
  src/main/java/seedu/address/storage/recruitment/XmlRecruitmentFileStorage.java
  src/main/java/seedu/address/storage/recruitment/XmlRecruitmentListStorage.java
  src/main/java/seedu/address/storage/recruitment/XmlSerializableRecruitmentList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecruitmentCard.java
  src/main/java/seedu/address/ui/RecruitmentListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecruitmentListCard.fxml
  src/main/resources/view/RecruitmentListPanel.fxml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalRecruitments.java
Labels: priority.high, type.story

#107 V1.2.2Dev Guide for recruitmentPost.
  docs/DeveloperGuide.adoc
Labels: update.documentation

#109 Slight updates to filter command and documentation
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/filterCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: type.enhancement, update.documentation

#112 Updated User Guide
  docs/UserGuide.adoc
Labels: update.documentation

#108 Update some comments.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/RecruitmentListChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/RecruitmentPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/parser/AddRecruitmentPostCommandParser.java
  src/main/java/seedu/address/model/recruitment/Post.java
  src/main/java/seedu/address/model/recruitment/ReadOnlyRecruitmentList.java
  src/main/java/seedu/address/model/recruitment/Recruitment.java
  src/main/java/seedu/address/model/recruitment/RecruitmentList.java
  src/main/java/seedu/address/model/recruitment/UniqueRecruitmentList.java
  src/main/java/seedu/address/storage/recruitment/XmlAdaptedRecruitment.java
  src/main/java/seedu/address/storage/recruitment/XmlSerializableRecruitmentList.java
  src/main/java/seedu/address/ui/RecruitmentCard.java
  src/main/java/seedu/address/ui/RecruitmentListPanel.java
Labels: type.enhancement, update.documentation

#115 Updating schedule comments in code and documentation
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/model/ScheduleListChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/model/addressbook/AddressBook.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/model/schedule/ReadOnlyScheduleList.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/ScheduleList.java
  src/main/java/seedu/address/model/schedule/Type.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/model/schedule/VersionedScheduleList.java
  src/test/java/seedu/address/model/schedule/VersionedScheduleListTest.java
  src/test/java/seedu/address/storage/XmlScheduleListStorageTest.java
Labels: update.documentation

#121 Modify pay v1.3
  src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
  src/main/java/seedu/address/logic/parser/ModifyPayCommandParser.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/storage/addressbook/XmlAdaptedPerson.java
Labels: priority.high, type.enhancement

#120 Mid-v1.3 Enhancements
  src/main/java/seedu/address/model/person/EmployeeIdContainsKeywordPredicate.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/model/person/DepartmentContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmployeeIdContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/PositionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, type.enhancement, update.testcase

#127 Added Portfolio adocs
  docs/AboutUs.adoc
  docs/team/chuazhenwei.adoc
  docs/team/limyisheng.adoc
  docs/team/ryanchen2018.adoc
  docs/team/xiiaopanda.adoc
  docs/team/zhihong8888.adoc
Labels: update.documentation

#129 Modify pay v1.3
  src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Salary.java
  src/test/java/seedu/address/model/person/SalaryTest.java
Labels: type.enhancement, v1.3

#124 V1.3 Enhancements
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/addressbook/AddressBook.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/addressbook/XmlAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpensesCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, status.ongoing, type.enhancement, update.testcase

#123 V1.3.1 Undo Redo bug fixed on schedule deleted cleared
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModelTypes.java
  src/main/java/seedu/address/model/VersionedModelList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpensesCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
Labels: priority.high, type.bug

#131 v1.3.3 GUI Enhancements
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.high, type.task

#133 V1.3.2 Schedule command to add leaves
  src/main/java/seedu/address/logic/commands/AddLeavesCommand.java
  src/main/java/seedu/address/logic/commands/AddWorksCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLeavesCommand.java
  src/main/java/seedu/address/logic/commands/DeleteWorksCommand.java
  src/main/java/seedu/address/logic/parser/AddLeavesCommandParser.java
  src/main/java/seedu/address/logic/parser/AddWorksCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteLeavesCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteWorksCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/model/schedule/Type.java
Labels: priority.high, v1.3

#135 Modify pay v1.3.3
  src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
Labels: priority.high, type.enhancement, v1.3

#134 v1.3.4 FilterCommand & AddCommand Enhancements
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmployeeIdContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/EmployeeIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmployeeIdContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/EmployeeIdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, type.enhancement, v1.3

#138 V1.3.3 Select Schedule, Clear Schedule
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/JumpToListScheduleRequestEvent.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SelectScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectScheduleCommandParser.java
  src/main/java/seedu/address/ui/ScheduleListPanel.java
Labels: priority.high

#130 Recruiment v1.3.1
  src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/recruitment/JobDescription.java
  src/main/java/seedu/address/model/recruitment/Post.java
  src/main/java/seedu/address/model/recruitment/Recruitment.java
  src/main/java/seedu/address/model/recruitment/WorkExp.java
  src/test/java/seedu/address/testutil/recruitment/RecruitmentBuilder.java
Labels: type.enhancement, v1.3

#143 V1.3.3 New commands: Select Expenses Command and Clear Expenses Command
  src/main/java/seedu/address/commons/events/ui/JumpToListExpensesRequestEvent.java
  src/main/java/seedu/address/logic/commands/ClearExpensesCommand.java
  src/main/java/seedu/address/logic/commands/SelectExpensesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectExpensesCommandParser.java
  src/main/java/seedu/address/ui/ExpensesListPanel.java
Labels: priority.high, type.story, v1.3

#141 V1.3 enhancements
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmployeeIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Position.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/EmployeeIdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmployeeIdTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/PositionTest.java
Labels: priority.high, type.enhancement, v1.3

#142 Modify pay v1.3.3
  src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
  src/main/java/seedu/address/model/person/Bonus.java
  src/main/java/seedu/address/model/person/Salary.java
Labels: priority.high, type.enhancement, v1.3

#147 Recruitment post v1.3.2
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/JumpToListRecruitmentPostRequestEvent.java
  src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectRecruitmentPostCommandParser.java
  src/main/java/seedu/address/model/recruitment/Post.java
  src/main/java/seedu/address/model/recruitment/RecruitmentList.java
  src/main/java/seedu/address/model/recruitment/UniqueRecruitmentList.java
  src/main/java/seedu/address/model/recruitment/WorkExp.java
  src/main/java/seedu/address/ui/RecruitmentListPanel.java
Labels: priority.high, type.enhancement, v1.3

#145 V1.3.5 Schedule
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddLeavesCommand.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/AddWorksCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLeavesCommand.java
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteWorksCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/VersionedModelList.java
  src/main/java/seedu/address/model/addressbook/DayHourGreeting.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/storage/schedule/XmlAdaptedSchedule.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecruitmentCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/address_book_32_old.png
  src/main/resources/images/background.jpg
  src/main/resources/images/border.jpg
  src/main/resources/images/border2.jpg
  src/main/resources/images/command_text_field.jpg
  src/main/resources/images/result_display.jpg
  src/main/resources/images/split_pane.jpg
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecruitmentListCard.fxml
  src/main/resources/view/ScheduleListCard.fxml
  src/test/data/XmlSerializableScheduleListTest/duplicateScheduleScheduleList.xml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/schedule/DateTest.java
  src/test/java/seedu/address/testutil/schedule/ScheduleBuilder.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, v1.3

#149 Recruitment v1.3.3
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/commands/SelectRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.high, type.enhancement, v1.3

#151 Recruitment v1.3.4
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ClearRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.high, type.enhancement, v1.3

#146 v1.3.7 FindCommand Enhancement
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high, status.ongoing, type.enhancement, v1.3

#155 Recruitment v1.3.5
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/commands/EditRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditRecruitmentPostCommandParser.java
  src/main/java/seedu/address/model/recruitment/Post.java
  src/main/java/seedu/address/model/recruitment/Recruitment.java
Labels: priority.high, type.story, v1.3

#156 UserGuide.adoc Update
  docs/UserGuide.adoc
Labels: priority.high, update.documentation, v1.3

#157 Recruitment v1.3.6
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/AddRecruitmentPostCommandParser.java
Labels: priority.high, type.enhancement, v1.3

#160 Update User guide
  docs/UserGuide.adoc
Labels: priority.high, update.documentation, v1.3

#158 v1.3.8 Bug fixing
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: priority.high, v1.3

#154 V1.3.5 User guide and minor updates
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddExpensesCommand.java
  src/main/java/seedu/address/logic/commands/ClearExpensesCommand.java
  src/main/java/seedu/address/logic/commands/RemoveExpensesCommand.java
  src/main/java/seedu/address/logic/commands/SelectExpensesCommand.java
  src/main/java/seedu/address/logic/parser/AddExpensesCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/expenses/MedicalExpenses.java
  src/main/java/seedu/address/model/expenses/MiscellaneousExpenses.java
  src/main/java/seedu/address/model/expenses/TravelExpenses.java
Labels: priority.high, type.enhancement, v1.3
