Repository CS2113-AY1819S1-T16-4/main, pull requests merged in 2018-11, with the labels that each got.

#164 V1.3.9 User guide update, Ui toolbar update, Ui.png update
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/resources/docs/images/Ui.png
  src/main/resources/images/border.jpg
  src/main/resources/images/split_pane.jpg
  src/main/resources/images/toolbar-selected.png
  src/main/resources/images/toolbar.jpg
  src/main/resources/view/DarkTheme.css
Labels: update.documentation

#167 UserGuide Update and Command Alias
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/resources/view/MainWindow.fxml
Labels: update.documentation

#168 V1.3.11 menu bar upgraded
  src/main/java/seedu/address/commons/events/ui/NewMenuBarCmdClickedEvent.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.high, type.enhancement

#174 User Guide update for expenses
  docs/UserGuide.adoc
Labels: update.documentation

#175 Recruitment v1.3.7
  docs/UserGuide.adoc
Labels: update.documentation

#176 Userguide update
  docs/UserGuide.adoc
Labels: update.documentation

#178 Bug fixed for FilterCommand
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: type.bug

#179 RecruitmentV1.3.8
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/recruitment/JobDescription.java
  src/main/java/seedu/address/model/recruitment/Post.java
Labels: priority.high, update.documentation

#181 Updated UserGuide
  docs/UserGuide.adoc
Labels: update.documentation

#182 Update Ui.png, userguide update
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/Ui_old.png
  src/main/java/seedu/address/logic/commands/AddExpensesCommand.java
  src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/commands/ClearExpensesCommand.java
  src/main/java/seedu/address/logic/commands/ClearRecruitmentPostCommand.java
  src/main/java/seedu/address/logic/commands/ClearScheduleCommand.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/resources/docs/images/Ui.png
  src/main/resources/view/ScheduleListCard.fxml
Labels: priority.high, update.documentation

#183 Updated UserGuide & Bug Fixing
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/DepartmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PositionContainsKeywordsPredicate.java
Labels: priority.high, type.bug, update.documentation

#186 V1.3.6 Added upper bound for expenses fields
  src/main/java/seedu/address/logic/commands/AddExpensesCommand.java
  src/main/java/seedu/address/model/expenses/MedicalExpenses.java
  src/main/java/seedu/address/model/expenses/MiscellaneousExpenses.java
  src/main/java/seedu/address/model/expenses/TravelExpenses.java
Labels: type.bug

#187 Updated modifyPay and modifyAllPay
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ModifyAllPayCommand.java
  src/main/java/seedu/address/logic/parser/ModifyAllPayCommandParser.java
  src/main/java/seedu/address/logic/parser/ModifyPayCommandParser.java
  src/main/java/seedu/address/model/person/Salary.java
Labels: priority.high, type.bug

#188 Update constrain msg
  src/main/java/seedu/address/model/recruitment/JobDescription.java
  src/main/java/seedu/address/model/recruitment/Post.java
Labels: priority.high, type.enhancement

#216 V1.4.0 Resolve work and leave schedule on same date, Userguide corrected
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddLeavesCommand.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/AddWorksCommand.java
  src/main/java/seedu/address/logic/commands/CalculateLeavesCommand.java
  src/main/java/seedu/address/model/schedule/DateComparator.java
  src/main/java/seedu/address/model/schedule/EmployeeIdComparator.java
Labels: priority.high, v1.4

#215 Bug fix for modifyAllPay
  src/main/java/seedu/address/logic/commands/ModifyAllPayCommand.java
Labels: type.bug, v1.4

#219 v1.4 Bug Fixing and Code Refactoring
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewexCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/expenses/ExpensesList.java
  src/main/java/seedu/address/model/expenses/UniqueExpensesList.java
  src/main/java/seedu/address/model/person/DateOfBirthContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/schedule/ScheduleList.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/DateOfBirthContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
Labels: priority.high, type.bug, update.documentation, v1.4

#221 V1.4.2 FindCommand Enhancement & Test Files
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/XmlSerializableRecruitmentListTest/typicalRecruitmentsRecruitmentList.xml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/BonusTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/EmployeeIdTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/PositionTest.java
  src/test/java/seedu/address/model/person/SalaryTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalRecruitments.java
Labels: priority.high, update.testcase, v1.4

#224 Modify pay v1.4 test files for modifyPayCommand
  src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Bonus.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ModifyPayCommandTest.java
  src/test/java/seedu/address/model/person/BonusTest.java
  src/test/java/seedu/address/testutil/ModSalaryDescriptorBuilder.java
Labels: update.testcase, v1.4

#226 New Test Files
  src/main/java/seedu/address/logic/commands/ModifyAllPayCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ModifyAllPayCommandTest.java
  src/test/java/seedu/address/testutil/ModAllSalaryDescriptorBuilder.java
Labels: update.testcase, v1.4

#225 Recruitment test files updatedV1.4.1
  src/test/java/seedu/address/model/recruitment/JobDescriptionTest.java
  src/test/java/seedu/address/model/recruitment/PostTest.java
  src/test/java/seedu/address/model/recruitment/WorkExpTest.java
Labels: priority.high, update.testcase, v1.4

#223 V1.4.3 Enhancements
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/recruitment/JobDescription.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.high, type.task, update.testcase, v1.4

#233 DeveloperGuide Update
  docs/DeveloperGuide.adoc
Labels: update.documentation

#234 V1.4.3 bug fix
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/TypeTest.java
  src/test/java/seedu/address/testutil/schedule/TypicalSchedules.java
Labels: priority.high, type.bug, v1.4

#231 Updated Developer Guide
  docs/images/UiClassDiagram.png
Labels: update.documentation, v1.4

#236 V1.4.4 Java adoc comment in java
  src/main/java/seedu/address/logic/commands/AddLeavesCommand.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/AddWorksCommand.java
  src/main/java/seedu/address/logic/commands/CalculateLeavesCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLeavesCommand.java
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteWorksCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectScheduleCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddWorksCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/model/schedule/DateComparator.java
  src/main/java/seedu/address/model/schedule/EmployeeIdComparator.java
  src/main/java/seedu/address/model/schedule/Type.java
  src/main/java/seedu/address/model/schedule/Year.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/ui/MenuBarTest.java
Labels: priority.high, update.documentation

#232 V1.4.2 Developer guide documentation update
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/expenses/XmlAdaptedExpenses.java
  src/test/data/XmlSerializableExpensesListTest/duplicateExpensesExpensesList.xml
  src/test/data/XmlSerializableExpensesListTest/typicalExpensesExpensesList.xml
  src/test/java/seedu/address/storage/XmlAdaptedExpensesTest.java
  src/test/java/seedu/address/storage/XmlSerializableExpensesListTest.java
  src/test/java/seedu/address/testutil/expenses/TypicalExpenses.java
Labels: priority.high, update.documentation, update.testcase, v1.4

#237 ModifyPay Parser test case
  src/main/java/seedu/address/logic/parser/ModifyPayCommandParser.java
  src/main/java/seedu/address/model/person/Salary.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ModifyPayCommandParserTest.java
Labels: update.testcase, v1.4

#238 Updated test case for ModifyAllPayParser
  src/main/java/seedu/address/logic/parser/ModifyAllPayCommandParser.java
  src/test/java/seedu/address/logic/parser/ModifyAllPayCommandParserTest.java
Labels: update.testcase, v1.4

#235 V1.4.6 Documentation & FilterCommand Updates
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/team/limyisheng.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/addressbook/AddressBook.java
  src/main/java/seedu/address/model/expenses/ExpensesList.java
  src/main/java/seedu/address/model/expenses/UniqueExpensesList.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmployeeIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Position.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/schedule/ScheduleList.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: priority.high, update.documentation

#241 Modify pay v1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ModifyPayCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ModifyAllPayCommand.java
  src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
  src/main/java/seedu/address/logic/parser/ModifyAllPayCommandParser.java
  src/main/java/seedu/address/logic/parser/ModifyPayCommandParser.java
  src/main/java/seedu/address/model/person/Bonus.java
Labels: priority.high, type.bug, update.documentation, v1.4

#245 Update documentation grammar error
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/zhihong8888.adoc
Labels: priority.high, status.ongoing, update.documentation

#244 V1.4.1 Update test cases
  src/main/java/seedu/address/logic/commands/AddExpensesCommand.java
  src/main/java/seedu/address/model/expenses/Expenses.java
  src/main/java/seedu/address/model/expenses/ExpensesAmount.java
  src/main/java/seedu/address/model/expenses/MedicalExpenses.java
  src/main/java/seedu/address/model/expenses/MiscellaneousExpenses.java
  src/main/java/seedu/address/model/expenses/TravelExpenses.java
  src/main/java/seedu/address/model/expenses/VersionedExpensesList.java
  src/test/data/XmlSerializableExpensesListTest/typicalExpensesExpensesListCopy.xml
  src/test/java/guitests/guihandles/ExpensesCardHandle.java
  src/test/java/guitests/guihandles/ExpensesListPanelHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/expenses/ExpensesListTest.java
  src/test/java/seedu/address/model/expenses/ExpensesTest.java
  src/test/java/seedu/address/model/expenses/UniqueExpensesListTest.java
  src/test/java/seedu/address/model/expenses/VersionedExpensesListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedExpensesTest.java
  src/test/java/seedu/address/storage/XmlSerializableExpensesListTest.java
  src/test/java/seedu/address/testutil/expenses/EditExpensesDescriptorBuilder.java
  src/test/java/seedu/address/testutil/expenses/ExpensesBuilder.java
  src/test/java/seedu/address/testutil/expenses/ExpensesListBuilder.java
  src/test/java/seedu/address/testutil/expenses/TypicalExpenses.java
  src/test/java/seedu/address/ui/ExpensesCardTest.java
  src/test/java/seedu/address/ui/ExpensesListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, update.testcase, v1.4

#246 Updated portfolio and test case
  docs/team/chuazhenwei.adoc
  src/test/java/seedu/address/logic/commands/ModifyAllPayCommandTest.java
  src/test/java/seedu/address/logic/commands/ModifyPayCommandTest.java
Labels: priority.high, update.documentation, update.testcase, v1.4

#243 Update Test filesV1.4.4
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/recruitment/PostContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/recruitment/RecruitmentListTest.java
  src/test/java/seedu/address/model/recruitment/RecruitmentTest.java
  src/test/java/seedu/address/model/recruitment/UniqueRecruitmentListTest.java
  src/test/java/seedu/address/model/recruitment/VersionedRecruitmentListTest.java
  src/test/java/seedu/address/testutil/TypicalRecruitments.java
  src/test/java/seedu/address/testutil/recruitment/EditPostDescriptorBuilder.java
  src/test/java/seedu/address/testutil/recruitment/RecruitmentListBuilder.java
Labels: priority.high, status.ongoing, update.testcase, v1.4

#240 V1.4.7 Documentation and Test File updates
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/filterCommandSequenceDiagram.png
  docs/team/limyisheng.adoc
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBookCopy.xml
  src/test/java/guitests/guihandles/RecruitmentCardHandle.java
  src/test/java/guitests/guihandles/RecruitmentListPanelHandle.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/RecruitmentCardTest.java
  src/test/java/seedu/address/ui/RecruitmentListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, update.documentation, update.testcase

#247 V1.4 Test files update
  src/main/java/seedu/address/model/VersionedModelList.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.high, update.testcase

#249 updated userguide and personal portfolio
  docs/UserGuide.adoc
  docs/team/chuazhenwei.adoc
Labels: priority.high, type.bug, update.documentation, update.testcase

#251 V1.4.8 Documentation Updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/limyisheng.adoc
Labels: priority.high, update.documentation, v1.4

#248 V1.4.3 Update test files
  src/main/java/seedu/address/logic/commands/AddExpensesCommand.java
  src/main/java/seedu/address/logic/parser/AddExpensesCommandParser.java
  src/main/java/seedu/address/model/expenses/ExpensesAmount.java
  src/test/data/XmlExpensesListStorageTest/invalidExpensesExpensesList.xml
  src/test/data/XmlSerializableExpensesListTest/invalidExpensesExpensesList.xml
  src/test/java/seedu/address/logic/commands/ClearExpensesCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemoveExpensesCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectExpensesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddExpensesCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveExpensesCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SelectExpensesCommandParserTest.java
  src/test/java/seedu/address/model/expenses/EmployeeIdExpensesContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/XmlAdaptedExpensesTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/expenses/TypicalExpenses.java
Labels: priority.high, update.testcase, v1.4

#254 V1.4.9 Documentation update
  docs/images/filterCommandSequenceDiagram.png
Labels: priority.high, update.documentation, v1.4

#253 Updated portfolio to include test cases PR
  docs/team/chuazhenwei.adoc
Labels: priority.high, update.documentation, v1.4

#256 Updates to filter feature sequence diagram
  docs/images/filterCommandSequenceDiagram.png
Labels: priority.high, update.documentation

#258 Remove unintentional merging of older portfolio
  docs/team/chuazhenwei.adoc
Labels: priority.high, update.documentation, v1.4

#259 Recruitment v1.4.5
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Recruitment/addRecruitmentPost.png
  docs/team/ryanchen2018.adoc
Labels: priority.high, update.documentation, v1.4

#260 RecruitmentV1.4.6
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Recruitment/deleteRecruitmentPost.png
  docs/images/Recruitment/editRecruitmentPost.png
  docs/images/Recruitment/selectRecruitmentPost.png
  docs/team/ryanchen2018.adoc
Labels: priority.high, update.documentation, v1.4

#261 V1.4 Update documentation dev guide
  docs/DeveloperGuide.adoc
  docs/team/zhihong8888.adoc
  src/main/java/seedu/address/logic/commands/DeleteWorksCommand.java
Labels: priority.high, update.documentation, v1.4

#267 Group all v2.0 features at the bottom of user guideV1.4.7
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, update.documentation, v1.4

#268 Update ppp and dev guide
  docs/DeveloperGuide.adoc
  docs/team/zhihong8888.adoc
Labels: priority.high, update.documentation

#273 V1.4 Update Ui.png
  docs/DeveloperGuide.adoc
  docs/images/Ui.png
  src/main/resources/docs/images/Ui.png
Labels: update.documentation, v1.4

#272 Recruitment v1.4.9
  docs/DeveloperGuide.adoc
  docs/team/ryanchen2018.adoc
  src/main/java/seedu/address/model/recruitment/JobDescription.java
Labels: priority.high, type.enhancement, v1.4

#271 Updated prerequisite for modifyPay and modifyAllPay manual testing
  docs/DeveloperGuide.adoc
  docs/team/chuazhenwei.adoc
Labels: priority.high, update.documentation, v1.4

#274 Update on develop guide and user guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/xiiaopanda.adoc
  src/main/java/seedu/address/logic/commands/AddExpensesCommand.java
Labels: update.documentation, v1.4

#275 Updated Pull Request
  docs/DeveloperGuide.adoc
Labels: priority.high, update.documentation, v1.4
